//login actions
export const GET_LOGIN_CREDS_LOADING = "GET_LOGIN_CREDS_LOADING";
export const GET_LOGIN_CREDS_SUCCESS = "GET_LOGIN_CREDS_SUCCESS";
export const GET_LOGIN_CREDS_FAILURE = "GET_LOGIN_CREDS_FAILURE";
export const RESET_LOGIN_CREDS = "RESET_LOGIN_CREDS";
