//login actions
export const GET_LOGIN_CREDS_LOADING = "GET_LOGIN_CREDS_LOADING";
export const GET_LOGIN_CREDS_SUCCESS = "GET_LOGIN_CREDS_SUCCESS";
export const GET_LOGIN_CREDS_FAILURE = "GET_LOGIN_CREDS_FAILURE";
export const RESET_LOGIN_CREDS = "RESET_LOGIN_CREDS";

export const GET_ALL_TICKET_STATUSES_LOADING = "GET_ALL_TICKET_STATUSES";
export const GET_ALL_TICKET_STATUSES_SUCCESS =
  "GET_ALL_TICKET_STATUSES_SUCCESS";
export const GET_ALL_TICKETS_STATUSES_FAILURE =
  "GET_ALL_TICKETS_STATUSES_FAILURE";

export const GET_ALL_TICKETS_BY_STATUS_LOADING =
  "GET_ALL_TICKETS_BY_STATUS_LOADING";
export const GET_ALL_TICKETS_BY_STATUS_SUCCESS =
  "GET_ALL_TICKETS_BY_STATUS_SUCCESS";
export const GET_ALL_TICKETS_BY_STATUS_FAILURE =
  "GET_ALL_TICKETS_BY_STATUS_FAILURE";
export const RESET_TICKETS_BY_STATUS = "RESET_TICKETS_BY_STATUS";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_ALL_ADMIN_USERS_SUCCESS = "GET_ALL_ADMIN_USERS_SUCCESS";
export const GET_ALL_ADMIN_USERS_FAILURE = "GET_ALL_ADMIN_USERS_FAILURE";
export const GET_ALL_ADMIN_USERS_LOADING = "GET_ALL_ADMIN_USERS_LOADING";
export const CHANGE_TICKET_ASSIGNEE = "CHANGE_TICKET_ASSIGNEE";
export const CHANGE_ASSIGNEE_ERROR = "CHANGE_ASSIGNEE_ERROR";
export const SHOW_CHANGE_ASSIGNEE_LOADER = "SHOW_CHANGE_ASSIGNEE_LOADER";
export const CLOSE_ERROR_MODAL = "CLOSE_ERROR_MODAL";
