//login actions
export const GET_LOGIN_CREDS_LOADING = "GET_LOGIN_CREDS_LOADING";
export const GET_LOGIN_CREDS_SUCCESS = "GET_LOGIN_CREDS_SUCCESS";
export const GET_LOGIN_CREDS_FAILURE = "GET_LOGIN_CREDS_FAILURE";
export const RESET_LOGIN_CREDS = "RESET_LOGIN_CREDS";

export const USER_LOGOUT = "USER_LOGOUT";

export const GET_ALL_TICKET_STATUSES_LOADING = "GET_ALL_TICKET_STATUSES";
export const GET_ALL_TICKET_STATUSES_SUCCESS =
  "GET_ALL_TICKET_STATUSES_SUCCESS";
export const GET_ALL_TICKETS_STATUSES_FAILURE =
  "GET_ALL_TICKETS_STATUSES_FAILURE";

export const GET_ALL_TICKETS_BY_STATUS_LOADING =
  "GET_ALL_TICKETS_BY_STATUS_LOADING";
export const GET_ALL_TICKETS_BY_STATUS_SUCCESS =
  "GET_ALL_TICKETS_BY_STATUS_SUCCESS";
export const GET_ALL_TICKETS_BY_STATUS_FAILURE =
  "GET_ALL_TICKETS_BY_STATUS_FAILURE";
export const RESET_TICKETS_BY_STATUS = "RESET_TICKETS_BY_STATUS";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_ALL_ADMIN_USERS_SUCCESS = "GET_ALL_ADMIN_USERS_SUCCESS";
export const GET_ALL_ADMIN_USERS_FAILURE = "GET_ALL_ADMIN_USERS_FAILURE";
export const GET_ALL_ADMIN_USERS_LOADING = "GET_ALL_ADMIN_USERS_LOADING";
export const CHANGE_TICKET_ASSIGNEE = "CHANGE_TICKET_ASSIGNEE";
export const CHANGE_ASSIGNEE_ERROR = "CHANGE_ASSIGNEE_ERROR";
export const SHOW_CHANGE_ASSIGNEE_LOADER = "SHOW_CHANGE_ASSIGNEE_LOADER";
export const CLOSE_ERROR_MODAL = "CLOSE_ERROR_MODAL";
export const GET_ALL_DEPARTMENTS_SUCCESS = "GET_ALL_DEPARTMENTS_SUCCESS";
export const GET_ALL_DEPARTMENTS_FAILURE = "GET_ALL_DEPARTMENTS_FAILURE";
export const SEARCH_USER = "SEARCH_USER";
export const SEARCH_USER_FAILURE = "SEARCH_USER_FAILURE";
export const ASSIGN_DEPT_TO_USER = "ASSIGN_DEPT_TO_USER";
export const SHOW_LOADER = "SHOW_LOADER";
export const SHOW_ERROR = "SHOW_ERROR";
export const GET_USER_ROLE = "GET_USER_ROLE";
export const CHANGE_USER_ROLE = "CHANGE_USER_ROLE";
export const CLEAN_MANAGE_ACCESS = "CLEAN_MANAGE_ACCESS";
export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const EDIT_ACCESS_ERROR = "EDIT_ACCESS_ERROR";
export const SET_USER_DEPARTMENT = "SET_USER_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const UPDATE_USER = "UPDATE_USER";

export const GET_ALL_REPLIES_LOADING = "GET_ALL_REPLIES_LOADING";
export const GET_ALL_REPLIES_SUCCESS = "GET_ALL_REPLIES_SUCCESS";
export const GET_ALL_REPLIES_FAILURE = "GET_ALL_REPLIES_FAILURE";
export const RESET_ALL_REPLIES = "RESET_ALL_REPLIES";

export const GET_EMPLOYEE_TICKET_STATUS_COUNT_LOADING =
  "GET_EMPLOYEE_TICKET_STATUS_COUNT_LOADING";
export const GET_EMPLOYEE_TICKET_STATUS_COUNT_SUCCESS =
  "GET_EMPLOYEE_TICKET_STATUS_COUNT_SUCCESS";
export const GET_EMPLOYEE_TICKET_STATUS_COUNT_FAILURE =
  "GET_EMPLOYEE_TICKET_STATUS_COUNT_FAILURE";
export const REST_EMPLOYEE_TICKET_STATUS_COUNT =
  "REST_EMPLOYEE_TICKET_STATUS_COUNT";

export const GET_EMPLOYEE_SLA_INFO_LOADING = "GET_EMPLOYEE_SLA_INFO_LOADING";
export const GET_EMPLOYEE_SLA_INFO_SUCCESS = "GET_EMPLOYEE_SLA_INFO_SUCCESS";
export const GET_EMPLOYEE_SLA_INFO_FAILURE = "GET_EMPLOYEE_SLA_INFO_FAILURE";
export const REST_EMPLOYEE_SLA_INFO = "REST_EMPLOYEE_SLA_INFO";
export const GET_USER_TICKETS = "GET_USER_TICKETS";
export const DASHBOARD_ERROR = "DASHBOARD_ERROR";
export const SHOW_DASHBOARD_LOADER = "SHOW_DASHBOARD_LOADER";
export const RESET_DASHBOARD = "RESET_DASHBOARD";
