import React from 'react';
import ReactDOM from 'react-dom';
import './scss/index.scss';
import { routes as Routes } from './routes/index';
import * as serviceWorker from './serviceWorker';
import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css';
import 'react-bootstrap-table2-paginator/dist/react-bootstrap-table2-paginator.min.css';
import 'bootstrap/dist/css/bootstrap.min.css';
ReactDOM.render(<Routes />, document.getElementById('root'));
serviceWorker.unregister();
